<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MiraiSpace.Platform.Avalonia\MiraiSpace.Platform.Avalonia.csproj" />
  </ItemGroup>
</Project>
