<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="DynamicData" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="ReactiveUI.Avalonia" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Application\MiraiSpace.Application\MiraiSpace.Application.csproj" />
    <ProjectReference Include="..\..\Extensibility\MiraiSpace.Extensibility.Abstractions\MiraiSpace.Extensibility.Abstractions.csproj" />
  </ItemGroup>
</Project>
