<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="DynamicData" />
    <PackageReference Include="MessagePipe" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="HanumanInstitute.MvvmDialogs" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.SourceGenerators" />
    <PackageReference Include="ReactiveUI.Binding" />
    <PackageReference Include="ReactiveUI.Binding.SourceGenerators" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Application\MiraiSpace.Application\MiraiSpace.Application.csproj" />
    <ProjectReference Include="..\..\Extensibility\MiraiSpace.Extensibility.Abstractions\MiraiSpace.Extensibility.Abstractions.csproj" />
  </ItemGroup>
</Project>
