<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MiraiSpace.Infrastructure.Api\MiraiSpace.Infrastructure.Api.csproj" />
    <ProjectReference Include="..\MiraiSpace.Infrastructure.Realtime\MiraiSpace.Infrastructure.Realtime.csproj" />
    <ProjectReference Include="..\MiraiSpace.Infrastructure.Storage\MiraiSpace.Infrastructure.Storage.csproj" />
    <ProjectReference Include="..\MiraiSpace.Platform.Desktop\MiraiSpace.Platform.Desktop.csproj" />
    <ProjectReference Include="..\MiraiSpace.Extensibility.Abstractions\MiraiSpace.Extensibility.Abstractions.csproj" />
    <ProjectReference Include="..\MiraiSpace.UI\MiraiSpace.UI.csproj" />
  </ItemGroup>
</Project>
