<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../build/Directory.Build.props" />
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ReactiveUI.Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Platform\MiraiSpace.Platform.Avalonia\MiraiSpace.Platform.Avalonia.csproj" />
    <ProjectReference Include="..\..\Presentation\MiraiSpace.Presentation\MiraiSpace.Presentation.csproj" />
    <ProjectReference Include="..\MiraiSpace.UI.Controls\MiraiSpace.UI.Controls.csproj" />
    <ProjectReference Include="..\MiraiSpace.UI.Icons\MiraiSpace.UI.Icons.csproj" />
    <ProjectReference Include="..\MiraiSpace.UI.Themes\MiraiSpace.UI.Themes.csproj" />
  </ItemGroup>
</Project>
