<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  
  
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Eremex.Avalonia.Controls" />
    <PackageReference Include="Eremex.Avalonia.Themes.DeltaDesign" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="ReactiveUI.Avalonia" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Platform\MiraiSpace.Platform.Avalonia\MiraiSpace.Platform.Avalonia.csproj" />
    <ProjectReference Include="..\..\Presentation\MiraiSpace.Presentation\MiraiSpace.Presentation.csproj" />
    <ProjectReference Include="..\MiraiSpace.UI.Controls\MiraiSpace.UI.Controls.csproj" />
    <ProjectReference Include="..\MiraiSpace.UI.Icons\MiraiSpace.UI.Icons.csproj" />
    <ProjectReference Include="..\MiraiSpace.UI.Themes\MiraiSpace.UI.Themes.csproj" />
  </ItemGroup>
</Project>
