<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../build/Directory.Build.props" />
  <ItemGroup>
    <PackageReference Include="Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Application\MiraiSpace.Application\MiraiSpace.Application.csproj" />
  </ItemGroup>
</Project>
