<Project Sdk="Microsoft.NET.Sdk.WebAssembly">

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)-browser</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
  </ItemGroup>
  
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\MiraiSpace.Infrastructure.Api\MiraiSpace.Infrastructure.Api.csproj" />
    <ProjectReference Include="..\..\Infrastructure\MiraiSpace.Infrastructure.Realtime\MiraiSpace.Infrastructure.Realtime.csproj" />
    <ProjectReference Include="..\..\Infrastructure\MiraiSpace.Infrastructure.Storage\MiraiSpace.Infrastructure.Storage.csproj" />
    <ProjectReference Include="..\..\Platform\MiraiSpace.Platform.Browser\MiraiSpace.Platform.Browser.csproj" />
    <ProjectReference Include="..\..\Extensibility\MiraiSpace.Extensibility.Abstractions\MiraiSpace.Extensibility.Abstractions.csproj" />
    <ProjectReference Include="..\..\GUI\MiraiSpace.UI\MiraiSpace.UI.csproj" />
  </ItemGroup>
</Project>
