<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MiraiSpace.UI.Icons\MiraiSpace.UI.Icons.csproj" />
  </ItemGroup>
</Project>
